### ISSUE TITLE
Manditory refIds

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#92]
As part of Vermont's review of NA 3.4 they expressed concern over the mandatory refId for studentLocatorResponses.  I also have trouble with our refIds being mandatory because the infrastructure mandates that on a create request they can be omitted (along the system responsible for Master Data Management of that object to set a reliable id.).  Should we just relax this generally?

**Comment by mattharris5** [comment]
Interesting question. I think I need more information to understand why it is an issue to generate a refid when returning a `studentLocatorResponse`. Given the ease with which refid's are created, and the fact that a studentLocatorResponse is always going to be a unique response to a query, why not include it? I don't have an issue with removing the requirement, because I don't think it would adversely affect the operation, but I don't see why it's a problem to keep it as is. Aren't all SIF 3 responses required to include a refid already? I know xSre includes that as a mandatory element.

@NathanClinton, any thoughts?

**Comment by NathanClinton** [comment]
studentLocatorResponse is only ever generated provider-side as a return object to a query (i.e. no posting), so I think it's appropriate to mandate a refId.  What's the argument to relax the requirement?

**Comment by 4pins** [comment]
NATB:  Got to keep them mandatory.  Omitting on create, is treated as a special case.
For studentLocatorResponses keep refId for follow up requests.

**Comment by 4pins** [comment]
Will try to address both sides concerns and bring back to SRE and VT.

**Comment by 4pins** [comment]
StudentLocatorResponses -> StudentLocatorResults

**Comment by 4pins** [comment]
I've managed to modify to reflect feedback from VT (/w HMH) and @vinceparedes.  I hope to upload before the SRE meeting tomorrow.
