### ISSUE TITLE
StateProvinceId in lea?

### ISSUE THREAD

**Issue by 4pins** [Access4Learning/NADM#95]
MA uses the StateProvinceId in LEAInfo, how should this record be conveyed in SIF 3?

Maybe through:
/leas​/lea​/externalIdList​

**Comment by 4pins** [comment]
This applies equally to "school."

**Comment by vinceparedes** [comment]
The idea from the global perspective is to use localId with a type of State/Province Id.  We could add words to this effect to the documentation tag.

**Comment by 4pins** [comment]
Sounds good, go for it (or let me know that I need to do it)!

**Comment by vinceparedes** [comment]
Documentation updated for leaType and schoolType. In order to do this, I created naLEAType and naSchoolType from copies of gLEAType and gSchoolType. This has been done in 3.4 in several places to allow us to customize objects from the global model. 

We should also create an organization type codeset.
